# Generated by Django 4.2.5 on 2023-10-01 15:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_order_panier'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Panier',
            new_name='Cart',
        ),
    ]
